version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CLIENT_NAME}
    restart: always
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: ${NGINX_NAME}
    ports:
      - ${NGINX_PORT}
    depends_on:
      - server
