version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CLIENT_NAME}
    restart: always
    ports:
      - ${CLIENT_PORT}
    volumes:
      - ${CLIENT_VOLUME_ROOT}
