version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CLIENT_NAME}
    restart: always
    ports:
      - ${CLIENT_PORT}
    volumes:
      - ${SERVER_VOLUME_ROOT}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      server-net:
        ipv4_address: ${SERVER_IP}
networks:
  server-net:
    name: ${NETWORK_NAME}
    ipam:
      config:
        - subnet: ${SUBNET_IP}
