version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CLIENT_NAME}
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      server-net:
        ipv4_address: ${CLIENT_IP}
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: ${NGINX_NAME}
    ports:
      - ${NGINX_PORT}
    depends_on:
      - server
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      server-net:
        ipv4_address: ${CLIENT_NGINX_IP}
networks:
  client-net:
    name: ${CLIENT_NETWORK_NAME}
    ipam:
      config:
        - subnet: ${CLIENT_SUBNET_IP}
